---
- name: maven configuration
  hosts: maven
  become: yes
  
  roles:
  - rsyncinit   
  - maven
   
- name: tomcat configuration
  hosts: tomcat
  become: yes
  
  roles:
  - rsyncinit
  - tomcat
