---
- name: Ensure that tomcat8 is present
  apt: 
   name: tomcat8
   state: present

- name: Ensure that tomcat8 is present
  apt: 
   name: rsync
   state: present
   
- name: Copy war file from remote host
  synchronize:
   mode: push
   dest: "{{ dest_war }}" #on server "tomcat"
   src: "{{ src_war }}" #on remote server "maven"
  delegate_to: "{{ maven_srv }}"
  notify:
   - restart tomcat