---
- name: Ensure maven and git is present
  apt:
   name: "{{ item }}"
   state: present
  with_items:
   - maven
   - git
   - rsync
   
#- name: Ensure dir for git is present
# file:
#   path: dest_war
#   state: directory
   
- name: git clone
  git:
   repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
   dest: "{{ dest_war }}"
   clone: yes

- name: maven package
  command: mvn package
  args:
   chdir: "{{ dest_war }}"

# tasks file for maven